{
  try {
    asyncPutStore.put(keyByteArray,versionedVal,null);
    fail("A put with required writes 2 should've failed for this setup");
  }
 catch (  Exception ve) {
    logger.info("Error occured as expected : " + ve.getMessage());
  }
  markAsDone(true);
}
