{
  if (e.getMessage().contains("Filesystem closed") || ExceptionUtils.recursiveClassEquals(e,AccessControlException.class)) {
    throw new VoldemortException("Got an IOException we cannot recover from while trying to " + action + ". Attempt # "+ attempt+ "/"+ maxAttempts+ ". Will not try again.",e);
  }
 else {
    logFailureAndWait(action,IO_EXCEPTION,attempt,e);
  }
}
