{
  log.info("StorePushTask.call() invoked for URL: " + url);
  invokeHooks(BuildAndPushStatus.PUSHING,url);
  try {
    runPushStore(props,url,buildOutputDir);
  }
 catch (  RecoverableFailedFetchException e) {
    log.warn("There was a problem with some of the fetches, " + "but a swap was still able to go through for URL: " + url,e);
    invokeHooks(BuildAndPushStatus.SWAPPED_WITH_FAILURES,url);
    throw e;
  }
catch (  Exception e) {
    log.error("Exception during push for URL: " + url,e);
    throw e;
  }
  invokeHooks(BuildAndPushStatus.SWAPPED,url);
  log.info("StorePushTask.call() finished for URL: " + url);
  return true;
}
