def _check_error(self, resp):
    if resp._has_error:
        raise VoldemortException(resp.error.error_message, resp.error.error_code)
