{
  if (e.getMessage().contains("Filesystem closed")) {
    throw new VoldemortException("Got an IOException we cannot recover from while trying to " + action + ". Attempt # "+ attempt+ "/"+ maxAttempts+ ". Will not try again.",e);
  }
 else {
    logger.error(logFailureMessage(action,IO_EXCEPTION,attempt),e);
  }
}
